# Generated by Django 5.2.4 on 2025-08-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_interval_minutes', models.PositiveIntegerField(default=15, help_text='How often to check domains for DNS changes (in minutes). Minimum: 1 minute.')),
                ('email_notifications_enabled', models.BooleanField(default=False, help_text='Whether to send email notifications when DNS changes are detected')),
                ('notification_email', models.EmailField(blank=True, help_text='Email address to send notifications to', max_length=254, null=True)),
                ('max_parallel_checks', models.PositiveIntegerField(default=10, help_text='Maximum number of domains to check in parallel')),
                ('dns_timeout_seconds', models.PositiveIntegerField(default=30, help_text='Timeout for DNS queries in seconds')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monitor Settings',
                'verbose_name_plural': 'Monitor Settings',
            },
        ),
    ]
