# Generated by Django 5.2.4 on 2025-08-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_monitorsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorsettings',
            name='continuous_monitoring_enabled',
            field=models.BooleanField(default=False, help_text='Enable continuous monitoring (starts new cycle immediately after completion)'),
        ),
        migrations.AddField(
            model_name='monitorsettings',
            name='min_check_interval_seconds',
            field=models.PositiveIntegerField(default=60, help_text='Minimum seconds between checks for the same domain (rate limiting). Minimum: 10 seconds'),
        ),
    ]
