# Generated by Django 5.2.4 on 2025-08-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_add_continuous_monitoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorsettings',
            name='continuous_monitoring_enabled',
            field=models.BooleanField(default=True, help_text='Enable continuous monitoring (starts new cycle immediately after completion)'),
        ),
    ]
