# Generated by Django 5.2.4 on 2025-08-04 12:33

from django.db import migrations


def enable_continuous_monitoring(apps, schema_editor):
    """Enable continuous monitoring for existing MonitorSettings instances"""
    MonitorSettings = apps.get_model('monitor', 'MonitorSettings')

    # Update all existing settings to enable continuous monitoring
    MonitorSettings.objects.filter(continuous_monitoring_enabled=False).update(
        continuous_monitoring_enabled=True
    )


def disable_continuous_monitoring(apps, schema_editor):
    """Reverse migration: disable continuous monitoring"""
    MonitorSettings = apps.get_model('monitor', 'MonitorSettings')

    # Update all settings to disable continuous monitoring
    MonitorSettings.objects.filter(continuous_monitoring_enabled=True).update(
        continuous_monitoring_enabled=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_add_continuous_monitoring'),
    ]

    operations = [
        migrations.RunPython(enable_continuous_monitoring, disable_continuous_monitoring),
    ]
