# Generated by Django 5.2.4 on 2025-08-04 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_enable_continuous_monitoring_by_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField(help_text='Raw HTML content of the homepage (without CSS/JS)')),
                ('status_code', models.PositiveIntegerField(help_text='HTTP status code from the request')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if snapshot capture failed', null=True)),
                ('is_initial_snapshot', models.BooleanField(default=False, help_text='Whether this is the initial snapshot when domain was first added')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this snapshot was captured')),
                ('domain', models.ForeignKey(help_text='Domain that was captured', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='monitor.domain')),
                ('record_log', models.OneToOneField(blank=True, help_text='Associated DNS check log entry (if snapshot was taken due to IP change)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='monitor.recordlog')),
            ],
            options={
                'verbose_name': 'Domain Snapshot',
                'verbose_name_plural': 'Domain Snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['domain', '-timestamp'], name='monitor_dom_domain__330d52_idx'), models.Index(fields=['is_initial_snapshot', '-timestamp'], name='monitor_dom_is_init_693442_idx')],
            },
        ),
    ]
