# Generated by Django 5.2.4 on 2025-08-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_add_domain_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPWhoisInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address this information belongs to', unique=True)),
                ('asn', models.CharField(blank=True, help_text='Autonomous System Number (e.g., AS13335)', max_length=20, null=True)),
                ('asn_description', models.TextField(blank=True, help_text='Description of the ASN', null=True)),
                ('organization', models.CharField(blank=True, help_text='Organization name', max_length=255, null=True)),
                ('isp', models.CharField(blank=True, help_text='Internet Service Provider', max_length=255, null=True)),
                ('country', models.CharField(blank=True, help_text='Country where IP is registered', max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, help_text='Two-letter country code', max_length=2, null=True)),
                ('registry', models.CharField(blank=True, help_text='Regional Internet Registry (e.g., ARIN, RIPE)', max_length=50, null=True)),
                ('network_cidr', models.CharField(blank=True, help_text='Network CIDR block', max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time this information was updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this information was first retrieved')),
                ('error_message', models.TextField(blank=True, help_text='Error message if WHOIS lookup failed', null=True)),
            ],
            options={
                'verbose_name': 'IP WHOIS Information',
                'verbose_name_plural': 'IP WHOIS Information',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['ip_address'], name='monitor_ipw_ip_addr_a61ab2_idx'), models.Index(fields=['asn'], name='monitor_ipw_asn_b56d42_idx'), models.Index(fields=['organization'], name='monitor_ipw_organiz_050ad8_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecordLogIPInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address (denormalized for easier querying)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this association was created')),
                ('ip_whois_info', models.ForeignKey(help_text='WHOIS information for the IP', on_delete=django.db.models.deletion.CASCADE, related_name='record_log_entries', to='monitor.ipwhoisinfo')),
                ('record_log', models.ForeignKey(help_text='DNS record log this IP information belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ip_info_entries', to='monitor.recordlog')),
            ],
            options={
                'verbose_name': 'Record Log IP Information',
                'verbose_name_plural': 'Record Log IP Information',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['record_log', 'ip_address'], name='monitor_rec_record__85a296_idx')],
                'unique_together': {('record_log', 'ip_address')},
            },
        ),
    ]
