# Generated by Django 5.2.4 on 2025-08-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_domain_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='domain',
            new_name='monitor_dom_is_acti_4b7a17_idx',
            old_name='monitor_dom_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='domain',
            new_name='monitor_dom_updated_1c8688_idx',
            old_name='monitor_dom_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='domain',
            new_name='monitor_dom_created_cf3662_idx',
            old_name='monitor_dom_created_idx',
        ),
    ]
